### PR TITLE
debug flag

### PR DESCRIPTION
**Pull request by SaulDoesCode**
Want to make running in ``debug_mode`` easier, adding a ``debug`` flag allows me to not have to edit the config file every time I want to debug.

### CODE REVIEW

**Comment by SaulDoesCode** [comment]
Also, consider using [flaggy](https://github.com/integrii/flaggy), since it allows you to set shorthand flags easilly.

```go
var configfile string
flaggy.String(&configfile , "c", "config", "tell air where to look for the configuration file")

if configfile == "" {
   configfile = "config.toml"
}
```

```bash
myapp -c ./private/config.toml
```

**Comment by SaulDoesCode** [comment]
It would also be nice if you could set the config file's location programmatically.

```go
air.ConfFile("./private/config.toml") // ...reinterpret
```

**Comment by SaulDoesCode** [comment]
And there should be a warning/error printed out, when air can't find the config.toml, instead of exiting abruptly

**Comment by aofei** [comment]
In this case, I think it would be more convenient to support a little more flags. Such as: `--address`, `--tls-cert-file`, `--tls-key-file` and other handy flags. What do you think?

**Comment by aofei** [comment]
> It would also be nice if you could set the config file's location programmatically.
> ...

I don't think so. Dynamically reloading a configuration file is not an easy task. After all, we have too many configuration items to use only when starting the server. So, I think, the configurations should not support dynamic reloading. Or we add a func (such as `Restart()`) to restart the server. But that's too much.

**Comment by SaulDoesCode** [comment]
Inside ``air.go``
```go
var ConfigFile = "config.toml"

var called = false
func Init(configfile string) {
 if called {
  return
}
called = true
 /* ... everything that was in init */ 
}
```

inside ``server.go``
```go
func Serve() {
  air.Config(ConfigFile)
}
```

^_ It's a bit rough but what if we did something like this?

Only reason it might be nice to set these things programmatically is so that the main Application using air can take back control of the flags, or at least, offer sensible defaults without making the end user think about flags or even try to remember them. But it's your call...

**Comment by SaulDoesCode** [comment]
Yes, gimme all the flags you got, I love it!

**Comment by aofei** [comment]
Yeah, you are right, Air should not dominate the flags. I designed it in the first place to facilitate development and deployment, but now it looks... stupid. A framework should never control the flags.

**Comment by aofei** [comment]
Hi @SaulDoesCode,

I think adding a `func Config(file string) error` might be good, but should it be called automatically in the `server#serve()`?

The `config.toml`:

```toml
address = "localhost:6677"
```

The `main.go`:

```go
package main

import "github.com/aofei/air"

func main() {
	air.Address = "localhost:7788"
	air.Serve()
}
```

The `air.Address` will be replaced with `localhost:6677` if there is an implicit call in the `air.Server()`.

**Comment by SaulDoesCode** [comment]
The user should not have to think about these things, just like the saying innocent until proven guilty, try to parse the config file, unless explicitly told not to.

I might go about it like this:
```go
var HasConfig = true

// ... do everything the same, normal if HasConfig

// in user-land
air.HasConfig = false
air.Address = ":2443" 
air.AppName = "A Big Idea"
// ...more config options

// back in Air-land
if !HasConfig {
  // skip parsing
}
```

When HasConfig is false don't parse any files
But if it's true, which is should be by default, then parse.

Though, perhaps, you should still retain a post-processing step for the config params,
a Config Digest
```go
// this is from another project
func digestConfig(config *Config) {
	if config.Private == "" {
		config.Private = "./private"
	}

	if config.Assets == "" {
		config.Assets = "./assets"
	}

	if config.Cache == "" {
		config.Cache = config.Private + "/cache"
	}

	if config.AutoCert && len(config.Whitelist) == 0 && config.Domain != "" {
		config.Whitelist = []string{config.Domain}
	}

       // [...more checks/defaults]
}
```
^- this project just maintains a global Config struct
it can populate the values from a file or from a user's manual setting.
But, it always run's the digest to check that values are valid

**Comment by SaulDoesCode** [comment]
Also, ``air.ConfigFile`` could be a useful option.

Then a user can set where to look before hand.

**Comment by aofei** [comment]
I prefer `air.Address` more than `air.Config.Address`, so I gave up using a `Config`-like struct stuff.

See 026794c7d9949001ab85ea6bb6b17fc96ac0d907, I decided to use the `ConfigFile`. What do you think?

**Comment by SaulDoesCode** [comment]
For this project that also makes sense because air runs as a singleton, so there's no conflicting instances to worry about anyway. So yeah, that's fine.

**Comment by SaulDoesCode** [comment]
Awesome ``ConfigFile`` simplifies things a lot!

**Pull request merged**
