### PR TITLE
Msgpack Support

### PR DESCRIPTION
**Pull request by SaulDoesCode**
Initial pr for msgpack support, hang tight a bit, I'll add some more commits just now.

### CODE REVIEW

**Comment by SaulDoesCode** [comment]
Ok basic MsgPack support is there.

just a thought I have it as ``res.WriteMsgpack``, do you think it should be ``res.WriteMsgPack`` instead?

**Comment by aofei** [comment]
I prefer the `Response#WriteMsgpack()`.

Msgpack -> MessagePack

Protobuf -> ProtocolBuffers

**Comment by SaulDoesCode** [comment]
https://stackoverflow.com/questions/6888900/mime-type-for-msgpack

We can add support for both, since msgpack is a lesser known format and people will have varying opinions.

**Comment by SaulDoesCode** [comment]
[From StackOverflow](https://stackoverflow.com/a/25886130/3943504)

> From Wikipedia : According to RFC 6838 (published in January 2013 : http://tools.ietf.org/html/rfc6838),
> any use of types in the "x." tree is strongly discouraged. Media types with names beginning with "x-" are
> no longer considered to be members of this tree since January 2013.
>
> Then use directly application/msgpack


However, if the mime-type is still a concern we could add in the following, just to give people the benefit of the doubt:

```go
switch mt {
case "application/json":
	err = json.NewDecoder(r.Body).Decode(v)
case "application/msgpack", "application/x-msgpack":
	err = msgpack.NewDecoder(r.Body).Decode(v)
case "application/xml":
	err = xml.NewDecoder(r.Body).Decode(v)
case "application/x-www-form-urlencoded", "multipart/form-data":
	err = b.bindParams(v, r.Params())
default:
	return errors.New("unsupported media type")
}
```

Not sure how to go about it with responses though

**Comment by aofei** [comment]
`case "application/msgpack", "application/x-msgpack":`, I think we should do this.

**Pull request merged**
